openapi: '3.0.0'
info:
  version: 1.0.0
  title: Game Theory API
  license:
    name: MIT
servers:
  - url: https://api.gametheory.com/v1
paths:
  /memberships:
    get:
      summary: List all memberships
      operationId: listMemberships
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of memberships
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Memberships'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a membership
      operationId: createMemberships
      responses:
        201:
          description: Membership created successfully
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /memberships/{membershipId}:
    get:
      summary: Info for a specific membership
      operationId: showMembershipById
      parameters:
        - name: membershipId
          in: path
          required: true
          description: The id of the membership to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Memberships'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /bookings:
    get:
      summary: List all bookings
      operationId: listBookings
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of bookings
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bookings'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a booking
      operationId: createBookings
      responses:
        201:
          description: Booking created successfully
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /facilities:
    get:
      summary: List all facilities
      operationId: listFacilities
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of facilities
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                $ref: '#/components/schemas/Facilities'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Membership:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Memberships:
      type: array
      items:
        $ref: '#/components/schemas/Membership'
    Booking:
      required:
        - id
        - facilityId
      properties:
        id:
          type: integer
          format: int64
        facilityId:
          type: string
        startTime:
          type: string
          format: date-time
    Bookings:
      type: array
      items:
        $ref: '#/components/schemas/Booking'
    Facility:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        sport:
          type: string
    Facilities:
      type: array
      items:
        $ref: '#/components/schemas/Facility'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
